import { Router } from 'express';
import { authRouter } from '../modules/auth/auth.routes';
import { userRouter } from '../modules/users/user.routes';
import { roleRouter } from '../modules/roles/role.routes';
import { analyticsRouter } from '../modules/analytics/analytics.routes';
import { permissionRouter } from '../modules/permissions/permission.routes';
import { studentRouter } from '../modules/students/student.routes';
import { schoolRouter } from '../modules/schools/school.routes';
import { branchRouter } from '../modules/branches/branch.routes';
import { parentRouter } from '../modules/parents/parent.routes';
import { feeRouter } from '../modules/fees/fee.routes';
import { paymentRouter } from '../modules/fees/payment.routes';
import { classRouter } from '../modules/academics/class.routes';
import { sectionRouter } from '../modules/academics/section.routes';
import { enrollmentRouter } from '../modules/academics/enrollment.routes';
import { subjectRouter } from '../modules/academics/subject.routes';
import { studentAttendanceRouter } from '../modules/attendance/student-attendance.routes';
import { teacherAttendanceRouter } from '../modules/attendance/teacher-attendance.routes';
import { timetableRouter } from '../modules/operations/timetable/timetable.routes';
import { examRouter } from '../modules/exams/exam.routes';
import { studentResultRouter } from '../modules/exams/student-result.routes';
import { libraryRouter } from '../modules/library/library.routes';
import { transportRouter } from '../modules/transport/transport.routes';
import { communicationRouter } from '../modules/communication/communication.routes';
import { departmentRouter } from '../modules/organization/department.routes';
import { teacherRouter } from '../modules/teachers/teacher.routes';

export const registerRoutes = (router: Router): void => {
  router.use('/auth', authRouter);
  router.use('/users', userRouter);
  router.use('/roles', roleRouter);
  router.use('/analytics', analyticsRouter);
  router.use('/permissions', permissionRouter);
  router.use('/students', studentRouter);
  router.use('/', schoolRouter);
  router.use('/', branchRouter);
  router.use('/parents', parentRouter);
  router.use('/', feeRouter);
  router.use('/', paymentRouter);
  router.use('/', classRouter);
  router.use('/', sectionRouter);
  router.use('/', enrollmentRouter);
  router.use('/', subjectRouter);
  router.use('/', studentAttendanceRouter);
  router.use('/', teacherAttendanceRouter);
  router.use('/', timetableRouter);
  router.use('/', examRouter);
  router.use('/', studentResultRouter);
  router.use('/', libraryRouter);
  router.use('/', transportRouter);
  router.use('/', communicationRouter);
  router.use('/', departmentRouter);
  router.use('/', teacherRouter);
};
