export const ROLE_HIERARCHY: Record<string, string[]> = {
  super_admin: [
    'super_admin',
    'school_owner',
    'school_admin',
    'school_principal',
    'teacher',
    'accountant',
    'registrar',
    'librarian',
    'parent',
    'student',
  ],
  school_owner: [
    'school_admin',
    'school_principal',
    'teacher',
    'accountant',
    'registrar',
    'librarian',
    'parent',
    'student',
  ],
  school_admin: [
    'school_principal',
    'teacher',
    'accountant',
    'registrar',
    'librarian',
    'parent',
    'student',
  ],
  school_principal: [
    'teacher',
    'accountant',
    'registrar',
    'librarian',
    'parent',
    'student',
  ],
  teacher: [],
  accountant: [],
  registrar: ['parent', 'student'],
  librarian: [],
  parent: [],
  student: [],
};

